from collections import Counter

textStr = 'AKALBIELCKCFJLDNSMBAIAFQEFAAIGJAUAKDSCFJLIACBASIDJMLBGBZCBLZCFQABZAODIKJCFJNCVADMIKEUAGACGEAIBZALAKKSZDFAGOAJASAFJDFBZALDNSMBAIGMGAJEFFCBEDFCKGALMIEBRCFJBZAAKALBIELCKGRGBANGBZCBNCVADMILCIGDSAICBAOAIACKKLIACBAJTRAKALBIELCKCFJLDNSMBAIAFQEFAAIGCBOSEOAVAASBZCBSIDQIAGGNDUEFQPDIOCIJOEBZDMIEFFDUCBEUAIAGACILZCFJDMBDPBZATDYCSSIDCLZAGBZAJASCIBNAFBDPAKALBIELCKCFJLDNSMBAIAFQEFAAIEFQCBOSELZCKKAFQAGGBMJAFBGBDSMGZBZANGAKUAGBDMFJAIGBCFJGDLEABRGCFJBALZFDKDQRGLDNSKAYEGGMAGEFCTIDCJAILDFBAYBBZCFOZCBGEFPIDFBDPBZANOAOCFBDMIGBMJAFBGOZABZAIBZARCIAACIFEFQCFMFJAIQICJMCBANEFDIDICJDLBDICBABDBCLVKAGDLEABRGNDGBSIAGGEFQSIDTKANGCFJMFLDUAIFAOOCRGDPGDKUEFQBZANOZABZAIEBGJAUAKDSEFQGRGBANGBZCBLCFKDLCBAPEIAPEQZBAIGEFBZANEJJKADPCTMIFEFQTMEKJEFQDILIACBEFQFAMIDSIDGBZABELGBZCBKDDVCFJPMFLBEDFKEVAFCBMICKKENTGDMIPCLMKBRCFJGBMJAFBGCIACBBZAPIDFBAJQADPIANCIVCTKAEFFDUCBEDFOZEKACJUCFLEFQBALZFDKDQEAGEGCBDMILDIAOACKGDBCVAZMNCFLDFFALBEDFGUAIRGAIEDMGKREFALAOASIEJADMIGAKUAGDFBZAPCNEKRKEVACBNDGSZAIAOALMKBEUCBAPCLMKBRGBMJAFBGCFJGBCPPAFLDMICQAACLZDBZAIGAUAIRGMLLAGGCFJCIABZAIAPDIBZALZCKKAFQAGTDBZEFBZALKCGGIDDNCFJEFKEPA'

def frequency(textStr, Counter):
    c = Counter(textStr)
    i = 1

    while(i <= len(textStr)):
        temp = c.most_common(i)
        i = i + 1
    
    print()
    print ('Word Frequency:', end="\n\n")
    for word in temp:
        print(word)
    print()
    return textStr

def replace(textStr):
    print ('Original Text:', textStr, end="\n\n")

    convertDict = {'T': 'b', 'A':'e', 'K':'l', 'L':'c',
                'B':'t', 'I':'r', 'E':'i', 'C':'a',
                'F':'n', 'J':'d', 'D':'o', 'N':'m',
                'S':'p', 'M':'u', 'Q':'g', 'G':'s',
                'U':'v', 'Z':'h', 'O':'w', 'V':'k',
                'R':'y', 'P':'f', 'Y':'x'}
    x = 0
    while (x < len(convertDict)):
        translated = textStr.maketrans(convertDict)
        txt = textStr.translate(translated)
        x = x + 1
    
    print ('Decoded text:', txt, end="\n\n")
    return txt

frequency(textStr, Counter)
replace(frequency(textStr, Counter))
frequency(replace(textStr), Counter)